(package "fuzzy"
         "0.3"
         "Fuzzy Matching")

(website-url "https://github.com/auto-complete/fuzzy-el")
(keywords "lisp" "fuzzy")

(package-file "fuzzy.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")
(source "melpa")

(depends-on "emacs" "24.3")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
